=== 2u841r/bd-location/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Generated schema for Root",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "number"
      },
      "name": {
        "type": "string"
      },
      "name_bn": {
        "type": "string"
      },
      "districts": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "number"
            },
            "division_name": {
              "type": "string"
            },
            "name": {
              "type": "string"
            },
            "name_bn": {
              "type": "string"
            },
            "subdistricts": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number"
                  },
                  "division_name": {
                    "type": "string"
                  },
                  "district_name": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "name_bn": {
                    "type": "string"
                  }
                },
                "required": [
                  "id",
                  "division_name",
                  "district_name",
                  "name",
                  "name_bn"
                ]
              }
            }
          },
          "required": [
            "id",
            "division_name",
            "name",
            "name_bn",
            "subdistricts"
          ]
        }
      }
    },
    "required": [
      "id",
      "name",
      "name_bn",
      "districts"
    ]
  }
}

=== 2u841r/bd-location/complete.json
[
  {
    "id": 1,
    "name": "Dhaka",
    "name_bn": "ঢাকা",
    "districts": [
      {
        "id": 1,
        "division_name": "dhaka",
        "name": "Dhaka",
        "name_bn": "ঢাকা",
        "subdistricts": [
          {
            "id": 801,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Dhaka North City Corporation",
            "name_bn": "ঢাকা উত্তর সিটি কর্পোরেশন"
          },
          {
            "id": 802,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Dhaka South City Corporation",
            "name_bn": "ঢাকা দক্ষিণ সিটি কর্পোরেশন"
          },
          {
            "id": 1,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Dhamrai",
            "name_bn": "ধামরাই"
          },
          {
            "id": 2,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Dohar",
            "name_bn": "দোহার"
          },
          {
            "id": 3,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Keraniganj",
            "name_bn": "কেরানীগঞ্জ"
          },
          {
            "id": 4,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Nawabganj",
            "name_bn": "নবাবগঞ্জ"
          },
          {
            "id": 5,
            "division_name": "dhaka",
            "district_name": "dhaka",
            "name": "Savar",
            "name_bn": "সাভার"
          }
        ]
      },
      {
        "id": 2,
        "division_name": "dhaka",
        "name": "Gazipur",
        "name_bn": "গাজীপুর",
        "subdistricts": [
          {
            "id": 6,
            "division_name": "dhaka",
            "district_name": "gazipur",
            "name": "Gazipur Sadar",
            "name_bn": "গাজীপুর সদর"
          },
          {
            "id": 7,
            "division_name": "dhaka",
            "district_name": "gazipur",
            "name": "Kaliakair",
            "name_bn": "কালিয়াকৈর"
          },
          {
            "id": 8,
            "division_name": "dhaka",
            "district_name": "gazipur",
            "name": "Kaliganj",
            "name_bn": "কালীগঞ্জ"
          },
          {
            "id": 9,
            "division_name": "dhaka",
            "district_name": "gazipur",
            "name": "Kapasia",
            "name_bn": "কাপাসিয়া"
          },
          {
            "id": 10,
            "division_name": "dhaka",
            "district_name": "gazipur",
            "name": "Sreepur",
            "name_bn": "শ্রীপুর"
          }
        ]
      },
      {
        "id": 3,
        "division_name": "dhaka",
        "name": "Narayanganj",
        "name_bn": "নারায়ণগঞ্জ",
        "subdistricts": [
          {
            "id": 11,
            "division_name": "dhaka",
            "district_name": "narayanganj",
            "name": "Narayanganj Sadar",
            "name_bn": "নারায়ণগঞ্জ সদর"
          },
          {
            "id": 12,
            "division_name": "dhaka",
            "district_name": "narayanganj",
            "name": "Araihazar",
            "name_bn": "আড়াইহাজার"
          },
          {
            "id": 13,
            "division_name": "dhaka",
            "district_name": "narayanganj",
            "name": "Bandar",
            "name_bn": "বন্দর"
          },
          {
            "id": 14,
            "division_name": "dhaka",
            "district_name": "narayanganj",
            "name": "Rupganj",
            "name_bn": "রূপগঞ্জ"
          },
          {
            "id": 15,
            "division_name": "dhaka",
            "district_name": "narayanganj",
            "name": "Sonargaon",
            "name_bn": "সোনারগাঁও"
          }
        ]
      },
      {
        "id": 4,
        "division_name": "dhaka",
        "name": "Narsingdi",
        "name_bn": "নরসিংদী",
        "subdistricts": [
          {
            "id": 16,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Narsingdi Sadar",
            "name_bn": "নরসিংদী সদর"
          },
          {
            "id": 17,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Belabo",
            "name_bn": "বেলাবো"
          },
          {
            "id": 18,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Monohardi",
            "name_bn": "মনোহরদী"
          },
          {
            "id": 19,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Palash",
            "name_bn": "পলাশ"
          },
          {
            "id": 20,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Raipura",
            "name_bn": "রায়পুরা"
          },
          {
            "id": 21,
            "division_name": "dhaka",
            "district_name": "narsingdi",
            "name": "Shibpur",
            "name_bn": "শিবপুর"
          }
        ]
      },
      {
        "id": 5,
        "division_name": "dhaka",
        "name": "Tangail",
        "name_bn": "টাঙ্গাইল",
        "subdistricts": [
          {
            "id": 22,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Tangail Sadar",
            "name_bn": "টাঙ্গাইল সদর"
          },
          {
            "id": 23,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Basail",
            "name_bn": "বাসাইল"
          },
          {
            "id": 24,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Bhuapur",
            "name_bn": "ভুয়াপুর"
          },
          {
            "id": 25,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Delduar",
            "name_bn": "দেলদুয়ার"
          },
          {
            "id": 26,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Dhanbari",
            "name_bn": "ধনবাড়ী"
          },
          {
            "id": 27,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Ghatail",
            "name_bn": "ঘাটাইল"
          },
          {
            "id": 28,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Gopalpur",
            "name_bn": "গোপালপুর"
          },
          {
            "id": 29,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Kalihati",
            "name_bn": "কালিহাতি"
          },
          {
            "id": 30,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Madhupur",
            "name_bn": "মধুপুর"
          },
          {
            "id": 31,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Mirzapur",
            "name_bn": "মির্জাপুর"
          },
          {
            "id": 32,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Nagarpur",
            "name_bn": "নাগরপুর"
          },
          {
            "id": 33,
            "division_name": "dhaka",
            "district_name": "tangail",
            "name": "Sakhipur",
            "name_bn": "সখিপুর"
          }
        ]
      },
      {
        "id": 6,
        "division_name": "dhaka",
        "name": "Kishoreganj",
        "name_bn": "কিশোরগঞ্জ",
        "subdistricts": [
          {
            "id": 34,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Kishoreganj Sadar",
            "name_bn": "কিশোরগঞ্জ সদর"
          },
          {
            "id": 35,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Astagram",
            "name_bn": "আস্তাগ্রাম"
          },
          {
            "id": 36,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Bajitpur",
            "name_bn": "বাজিতপুর"
          },
          {
            "id": 37,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Bhairab",
            "name_bn": "ভৈরব"
          },
          {
            "id": 38,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Hossainpur",
            "name_bn": "হোসেনপুর"
          },
          {
            "id": 39,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Itna",
            "name_bn": "ইটনা"
          },
          {
            "id": 40,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Karimganj",
            "name_bn": "করিমগঞ্জ"
          },
          {
            "id": 41,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Katiadi",
            "name_bn": "কটিয়াদি"
          },
          {
            "id": 42,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Kuliarchar",
            "name_bn": "কুলিয়ারচর"
          },
          {
            "id": 43,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Mithamain",
            "name_bn": "মিঠামাইন"
          },
          {
            "id": 44,
            "division_name": "dhaka",
            "district_name": "kishoreganj",
            "name": "Nikli",
            "name_bn": "নিকলী"
          },
          {
            "id": 45,
